[workspace]
resolver = "2"

members = ["crates/futures-signals-observable", "crates/futures-signals-observable-derive", "crates/test-lib"]

[workspace.dependencies]
futures = "0.3.x"
futures-signals = "0.3.x"
